name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Copy jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: target/app.jar
          target: ~/app/CICDpractice/
      
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app/CICDpractice
            docker-compose down
            docker-compose build
            docker-compose up -d
